name: test
on:
  pull_request:
    branches: [main]
jobs:
  git-log-test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get merged PR list
        run: |
          git branch -a
          git diff remotes/origin/${{ github.base_ref }}..remotes/origin/${{ github.head_ref }}
